- hosts:
  - all
  roles:
    - {role: os_common, tags: "os_common"} 

- hosts:
  - develop
  roles:
    - {role: developtools/vim, tags: "developtools/vim"} 
    - {role: developtools/ansible-go, tags: "developtools/ansible-go"} 

- hosts:
  - jenkins
  roles:
    - {role: jenkins, tags: "jenkins"} 

- hosts:
  - sample
  roles:
    - {role: sample, tags: "sample"} 

- hosts:
  - zabbix-server
  roles:
    - {role: zabbix-server, tags: "zabbix-server"} 

- hosts:
  - docker
  roles:
    - {role: docker, tags: "docker"} 

- hosts:
  - docker_mackerel
  roles:
    - {role: docker_mackerel, tags: "docker_mackerel"} 
