- name: git install
  become: yes
  yum: name=git state=latest

- name: jdk install
  become: yes
  yum: name=java-1.8.0-openjdk state=latest

- name: epel install
  become: yes
  yum: name=epel-release state=latest

- name: htop install
  become: yes
  yum: name=htop state=latest

- name: change vm.swappiness of tuned.conf
  become: yes
  lineinfile: >
    dest=/usr/lib/tuned/virtual-guest/tuned.conf
    regexp='^vm.swappiness = '
    line='vm.swappiness = 0'
  when: ansible_distribution_major_version == 7
