- name: copy motd ( include server fqdn, i3_env, i3_template information )
  template:
    src: motd
    dest: /etc/motd
    mode: 0644
    owner: root
    group: root
    backup: no
  when: i3_template is defined
